Astronomy_words = [
"Astronomy",
"Astrology",
"Astrophysics",
"Astrophotography",
"Supernova",
"Asteroid",
"Asteroid Belt",
"Asteroid Hole",
"Asteroid Mining",
"Observatory",
"Astronomer",
"Astronomical",
"Astronomical Object",
"Astronomical Observation",
"Cosmic",
"Cosmology",
"Geocentric",
"Quasar",
"Quasar Burst",
"Interstellar",
"Interstellar Medium",
"Eclipse",
"Exoplanet",
"Spectroscopy",
"Elliptical",
"Elliptical Galaxy",
"Elliptical Giant",
"Astrobiology",
"Astrobiological",
"Gravitational",
"Gravitational Wave",
"Solstice",
 "Nebula",
  "Celestial Body",
  "Black Hole",
  "Asteroid Belt",
  "Solar Flare",
  "Heliocentric Model",
  "Interstellar Medium",
  "Galaxy Cluster",
  "Pulsar",
  "Geocentric Model",
  "Planetary Nebula",
  "Exoplanet",
  "Celestial Sphere",
  "Redshift",
  "Cosmic Dust",
  "Event Horizon",
  "Astrobiology",
  "Radio Telescope",
  Celestial Navigation",
  Dark Matter,
  Neutron Star,
  Comet Tail,
  Ecliptic Plane,
  Lunar Crater,
  Stellar Fusion,
  Quasar,
  White Dwarf,
  Oort Cloud,
  Solar Wind,
  Galactic Nucleus,
  Doppler Effect,
  Hubble's Law,
  Kuiper Belt,
  Cosmic Inflation,
  Magnetosphere,
  Cosmic Ray,
  Zenith,
  Perihelion,
  Aphelion,
  Equinox,
  Solstice,
  Celestial Mechanics,
  Precession,
  Roche Limit,
  Lunar Eclipse,








  


]