Astronomy__words = [
"Astronomy",
"Astrology",
"Astrophysics",
"Astrophotography",
"Supernova",
"Asteroid",
"Asteroid Belt",
"Asteroid Hole",
"Asteroid Mining",
"Observatory",
"Astronomer",
"Astronomical",
"Astronomical Object",
"Astronomical Observation",
"Cosmic",
"Cosmology",
"Geocentric",
"Quasar",
"Quasar Burst",
"Interstellar",
"Interstellar Medium",
"Eclipse",
"Exoplanet",
"Spectroscopy",
"Elliptical",
"Elliptical Galaxy",
"Elliptical Giant",
"Astrobiology",
"Astrobiological",
"Gravitational",
"Gravitational Wave",
"Solstice",
 "Nebula",
  "Celestial Body",
  "Black Hole",
  "Asteroid Belt",
  "Solar Flare",
  "Heliocentric Model",
  "Interstellar Medium",
  "Galaxy Cluster",
  "Pulsar",
  "Geocentric Model",
  "Planetary Nebula",
  "Exoplanet",
  "Celestial Sphere",
  "Redshift",
  "Cosmic Dust",
  "Event Horizon",
  "Astrobiology",
  "Radio Telescope",
  "Celestial Navigation",
  "Dark Matter",
  "Neutron Star",
  "Comet Tail",
  "Ecliptic Plane",
  "Lunar Crater",
  "Stellar Fusion",
  "White Dwarf",
  "Oort Cloud",
  "Solar Wind",
  "Galactic Nucleus",
  "Doppler Effect",
  "Hubble's Law",
  "Kuiper Belt",
  "Cosmic Inflation",
  "Magnetosphere",
  "Cosmic Ray",
  "Zenith",
  "Perihelion",
  "Aphelion",
  "Equinox",
  "Celestial Mechanics",
  "Precession",
  "Roche Limit",
  "Celestial Mechanics",
  "Planetary Ring",
  "Helioseismology",
  "Heliosphere",
  "Cosmic String",
  "Opaque Nebula", 
  "Submillimeter Astronomy",
  "Celestial Equator",
  "Hubble Space Telescope",
  "Elliptical Orbit",
  "Gravitational Lens",
  "Galactic Halo",
  "Dark Energy",
  "Celestial Mechanics",
  "Celestial Pole",
  "Stellar Parallax",
  "Cosmogony",
  "Tidal Forces",
  "Star Cluster",
  "Asterism",
  "Circumpolar",
  "Photosphere",
  "Rayleigh Scattering",
  "Space-time",
  "Nebular Hypothesis",
  "Astrometry",
  "Extragalactic",
]







  

